apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentication
  namespace: ${ARGOCD_NAMESPACE}
spec:
  destination:
    namespace: authentication
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    repoURL: oci://${AUTHENTICATED_REGISTRY_REPOSITORY_URL}/authentication
    targetRevision: latest
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
